refactor(ci): remove async->sync python conversion check; use basedpyright in precommit hook and PR checks; add 'yarn docs' in PR check
Signed-off-by: MDzaja <mirkodzaja0@gmail.com>

diff --git a/.github/workflows/pr_checks.yaml b/.github/workflows/pr_checks.yaml
--- a/.github/workflows/pr_checks.yaml
+++ b/.github/workflows/pr_checks.yaml
@@ -13,6 +13,9 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  POETRY_VIRTUALENVS_IN_PROJECT: true
+
 jobs:
   go-work:
     name: Go work
@@ -74,6 +77,26 @@ jobs:
           working-directory: libs/computer-use
           args: --timeout=5m ./...
 
+  lint-python:
+    name: Python lint
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+      - name: Install Dependencies
+        run: |
+          corepack enable
+          yarn install --immutable
+          python -m pip install --upgrade pip
+          pip install "poetry==2.1.3"
+          poetry install
+      - name: Lint Python Code
+        run: |
+          source "$(poetry env info --path)/bin/activate"
+          yarn lint:py
+
   format-lint-api-clients:
     name: Format, lint and generate API clients
     runs-on: ubuntu-latest
@@ -93,20 +116,22 @@ jobs:
       - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install "isort>=5.10.0,<6.0.0" "black[jupyter]>=23.1.0,<24.0.0" "nbqa>=1.9.1,<2.0.0 " "pylint>=3.3.4,<4.0.0" "unasync>=0.6.0,<0.7.0" "poetry==2.1.3"
+          pip install "poetry==2.1.3"
+          poetry install
       - run: corepack enable
       - name: generate-api-clients
         run: |
+          source "$(poetry env info --path)/bin/activate"
           go install github.com/swaggo/swag/cmd/swag@v1.16.4
           echo -e 'DEFAULT_PACKAGE_VERSION=0.0.0-dev\n\nPYPI_PKG_VERSION=\nNPM_PKG_VERSION=\nNPM_TAG=\nPYPI_TOKEN=\nNPM_TOKEN=' > .env
           yarn install --immutable
           mkdir -p dist/apps/api
           yarn generate:openapi && yarn nx run-many --target=generate:api-client --all --parallel=false
-          yarn sdk-python:generate-sync
           yarn lint:fix
           yarn format
           poetry lock
-          git diff --exit-code || (echo "Code not formatted or linting errors! Hint: 'yarn generate:api-client', 'yarn sdk-python:generate-sync', 'yarn lint:fix' and commit" && exit 1)
+          yarn docs
+          git diff --exit-code || (echo "Code not formatted or linting errors! Hint: 'yarn generate:api-client', 'yarn lint:fix', 'yarn docs' and commit" && exit 1)
 
   build:
     runs-on: ubuntu-latest
